/// <reference path="../AA/at.aa.d.ts" />
/// <reference path="at.generic-event-vars.d.ts" />
/// <reference path="../AA/at.stdFunctions.d.ts" />
// ASI Table Arrays are also accessible via their name in all caps, no spaces.

declare var timeElapsedMin: undefined
declare var timeElapsedHours: undefined
declare var endTime: undefined
declare var dateLogged: undefined
declare var timeLogSeq: undefined
declare var timeLogModel: undefined
declare var wfTimeOT: String
declare var wfTimeBillable: String
declare var timeAccountingArray: undefined
declare var wfStaffUserID: String
declare var wfProcess: String
declare var wfActionByDept: String
declare var wfActionByUserID: String
declare var wfActionByObj: SysUserModel
declare var wfActionBy: SysUserModel
declare var wfHours: String
declare var wfDue: ScriptDateTime
declare var wfNote: null
declare var wfComment: String
declare var wfStep: number
declare var wfProcessID: number
declare var wfDateMMDDYYYY: string
declare var wfDate: String
declare var wfStatus: String
declare var wfTask: String
