/// <reference path="../AA/at.aa.d.ts" />
// ASI Table Arrays are also accessible via their name in all caps, no spaces.

declare var timeElapsedMin: undefined
declare var timeElapsedHours: undefined
declare var endTime: undefined
declare var startTime: number
declare var dateLogged: undefined
declare var timeLogSeq: undefined
declare var timeLogModel: undefined
declare var i: number
declare var wfTimeOT: String
declare var wfTimeBillable: String
declare var timeAccountingArray: undefined
declare var wfStaffUserID: String
declare var wfProcess: String
declare var wfActionByDept: String
declare var wfActionByUserID: String
declare var wfActionByObj: SysUserModel
declare var wfActionBy: SysUserModel
declare var wfHours: String
declare var wfDue: ScriptDateTime
declare var wfNote: null
declare var wfComment: String
declare var wfStep: number
declare var wfProcessID: number
declare var wfDateMMDDYYYY: string
declare var wfDate: String
declare var wfStatus: String
declare var wfTask: String
declare var prefix: string
declare var bvr3: ScriptResult<BizDomainScriptModel>
declare var bvr1: ScriptResult<BizDomainScriptModel>
declare var doScripts: boolean
declare var doStdChoices: boolean
declare var controlFlagStdChoice: string
declare var bzr: boolean
declare var SAScript: null
declare var SA: null
declare var useSA: boolean
declare var useCustomScriptFile: boolean
declare var SCRIPT_VERSION: number
declare var documentOnly: boolean
declare var preExecute: string
declare var controlString: string
declare var INCLUDE_VERSION: string
declare var parentCapString: string
declare var capDetailObjResult: ScriptResult<CapDetailScriptModel|undefined>
declare var currentUserGroupObj: UserGroupModel
declare var parentCapId: boolean
declare var feeFactor: String
declare var partialCap: boolean
declare var AInfo: [{ [key: string]: any }]
declare var capDetail: CapDetailScriptModel
declare var balanceDue: number
declare var feesInvoicedTotal: number
declare var houseCount: number
declare var calcValue: number
declare var estValue: number
declare var parcelArea: number
declare var fileDateYYYYMMDD: string
declare var fileDate: string
declare var fileDateObj: ScriptDateTime
declare var capStatus: String
declare var capName: null
declare var appTypeString: String
declare var appTypeAlias: String
declare var appTypeResult: CapTypeModel
declare var capIDString: String
declare var cap: CapScriptModel
declare var capId: CapIDModel
declare var servProvCode: String
declare var sysDateMMDDYYYY: string
declare var sysDate: ScriptDateTime
declare var publicUser: boolean
declare var publicUserID: null
declare var currentUserGroup: String
declare var systemUserObj: SysUserModel
declare var currentUserID: String
declare var paymentPeriodList: undefined
declare var feeSeqList: undefined
declare var br: string
declare var debug: string
declare var message: string
declare var startDate: undefined
declare var vEventName: String
declare var vScriptName: String
declare var cancel: boolean
declare var GLOBAL_VERSION: number
declare var maxEntries: number
declare var enableVariableBranching: boolean
declare var useTaskSpecificGroupName: boolean
declare var useAppSpecificGroupName: boolean
declare var disableTokens: boolean
declare var showDebug: boolean
declare var showMessage: boolean
declare var vLevel: number
declare var loopk: string
declare var OCCUPANCYTYPE: undefined
declare var CONSTRUCTIONTYPE: undefined
declare var getCapResult: ScriptResult<any>
declare var fTask: TaskItemScriptModel
declare var wfTaskObj: TaskItemScriptModel
declare var stopBranch: boolean
declare var loopGlob: string
